version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-demo
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./frontend:/usr/share/nginx/html/frontend:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: node:18-alpine
    container_name: backend-service
    command: node app.js
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge